version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: book
      MYSQL_USER: book
      MYSQL_PASSWORD: koscom
      MYSQL_ROOT_PASSWORD: koscom
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./data:/var/lib/mysql

#  rabbitmq:
#    image: rabbitmq:3.8.5-management
#    environment:
#      RABBITMQ_ERLANG_COOKIE: 'secretCookie'
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: 'adminSecret'
#    ports:
#    - 5672:5672
#    - 15672:15672